### ISSUE TITLE
TODO for 25.x.y

### ISSUE THREAD

**Issue by bvlj** [LuCEresearchlab/jtamaro#7]
To-Do list for next year's version of the library (API breaking changes)

- [x] Lazy Sequences removal
- [x] Make all methods are not used to produce _new_ Sequences instance methods
- [ ] Rotation degrees double to int to avoid confusion between deg/rad
- [x] Better hide classes and methods that are not supposed to be used by students
- [x] Modifiers for InputEvents (shift / ctrl / alt...)
- [x] `Points.*MIDDLE*` to `Points.*CENTER*` (match pytamaro names)
